name: "tracksuit_data_technical_test"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "tracksuit_data_technical_test"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  +persist_docs:
    relation: true
    column: true
    
seeds:
  tracksuit_data_technical_test:
    raw_survey_data:
      +column_types:
        data: json

    raw_respondent_demographics:
      +column_types:
        data: json

    raw_brand_information:
      +column_types:
        data: json


